sudo: required
language: generic
services:
  - docker
env:
  global:
    - ENCRYPTION_LABEL: "bedcd13b0faf"
before_install:
  - docker pull angelrb/botleague
script:
  - docker run -it -v $(pwd):/arena angelrb/botleague /main.rb Angelmmiguel andresgomezfrr
after_success:
  # - ./deploy.sh
